spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # 실제로는 별도 Authorization Server URL
          # 여기서는 자체 서명 검증을 위해 로컬 파일 공개키 사용
          public-key-location: classpath:public.pem

# JWT 설정
jwt:
  private-key: classpath:private.pem
  public-key: classpath:public.pem
  issuer: https://auth.example.com
  expiration: 3600

logging:
  level:
    org.springframework.security: DEBUG
    com.example.oauth_resource_server: DEBUG

# 서버 포트 설정
server:
  port: 8080